name: ecommerce
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  carousel_slider: null
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: null
  go_router: 
  smooth_page_indicator: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Muli
      fonts:
        - asset: assets\fonts\muli/Muli-Bold.ttf
        - asset: assets\fonts\muli/Muli-BoldItalic.ttf
        - asset: assets\fonts\muli/Muli-ExtraLight.ttf
        - asset: assets\fonts\muli/Muli-ExtraLightItalic.ttf
        - asset: assets\fonts\muli/Muli-Italic.ttf
        - asset: assets\fonts\muli/Muli-Light.ttf
        - asset: assets\fonts\muli/Muli-LightItalic.ttf
        - asset: assets\fonts\muli/Muli-Semi-BoldItalic.ttf
        - asset: assets\fonts\muli/Muli-SemiBold.ttf
        - asset: assets\fonts\muli/Muli.ttf
